In [48]:
texts = [
    "cổ phiếu ngân hàng tăng mạnh",
    "thị trường chứng khoán giảm điểm",
    "doanh thu quý này tăng cao",
    "lợi nhuận doanh nghiệp vượt kỳ vọng",
    "đội tuyển bóng đá thắng trận",
    "ca sĩ ra mắt album mới",
    "du lịch hè rất nhộn nhịp",
    "bộ phim mới đạt doanh thu phòng vé cao",
]

# 1 = Kinh tế/Kinh doanh, 0 = Không phải
labels = [1, 1, 1, 1, 0, 0, 0, 0]

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.3, random_state=42)


In [50]:
print("Train: ", X_train)
print("Test: ", X_test)

Train:  ['bộ phim mới đạt doanh thu phòng vé cao', 'doanh thu quý này tăng cao', 'đội tuyển bóng đá thắng trận', 'lợi nhuận doanh nghiệp vượt kỳ vọng', 'du lịch hè rất nhộn nhịp']
Test:  ['thị trường chứng khoán giảm điểm', 'ca sĩ ra mắt album mới', 'cổ phiếu ngân hàng tăng mạnh']


In [51]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [52]:
max_words = 100

tokenizer = Tokenizer(max_words)
tokenizer.fit_on_texts(X_train) # tạo từ điển (vocabulary)

print(tokenizer.word_index)

{'doanh': 1, 'thu': 2, 'cao': 3, 'bộ': 4, 'phim': 5, 'mới': 6, 'đạt': 7, 'phòng': 8, 'vé': 9, 'quý': 10, 'này': 11, 'tăng': 12, 'đội': 13, 'tuyển': 14, 'bóng': 15, 'đá': 16, 'thắng': 17, 'trận': 18, 'lợi': 19, 'nhuận': 20, 'nghiệp': 21, 'vượt': 22, 'kỳ': 23, 'vọng': 24, 'du': 25, 'lịch': 26, 'hè': 27, 'rất': 28, 'nhộn': 29, 'nhịp': 30}


In [53]:
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

print(X_train)
print(X_train_seq)

['bộ phim mới đạt doanh thu phòng vé cao', 'doanh thu quý này tăng cao', 'đội tuyển bóng đá thắng trận', 'lợi nhuận doanh nghiệp vượt kỳ vọng', 'du lịch hè rất nhộn nhịp']
[[4, 5, 6, 7, 1, 2, 8, 9, 3], [1, 2, 10, 11, 12, 3], [13, 14, 15, 16, 17, 18], [19, 20, 1, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30]]


In [54]:
# Các câu có độ dài khác nhau → cần cùng kích thước
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tham số	                                     Ý nghĩa
# padding='post'	                        thêm số 0 vào cuối
# truncating='pre' (default)	           cắt ở đầu
# truncating='post'	                       cắt ở cuối ✅

max_len = 6
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len, padding='post')

print(X_train_seq)
print(X_train_pad)

[[4, 5, 6, 7, 1, 2, 8, 9, 3], [1, 2, 10, 11, 12, 3], [13, 14, 15, 16, 17, 18], [19, 20, 1, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30]]
[[ 7  1  2  8  9  3]
 [ 1  2 10 11 12  3]
 [13 14 15 16 17 18]
 [20  1 21 22 23 24]
 [25 26 27 28 29 30]]


In [55]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense

model = Sequential([
    Embedding(input_dim=100, output_dim=16, input_length=max_len),
    Conv1D(filters=32, kernel_size=3, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [56]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

import numpy as np
model.fit(
    X_train_pad,
    np.array(y_train),
    epochs=10,
    verbose=1
)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 893ms/step - accuracy: 0.6000 - loss: 0.6949
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6000 - loss: 0.6917
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8000 - loss: 0.6885
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8000 - loss: 0.6853
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8000 - loss: 0.6825
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.6802
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.6776
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.6750
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.6725
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.6699


In [57]:
loss, acc = model.evaluate(X_test_pad, np.array(y_test))
print("Test Accuracy:", acc)

# thử câu mới
new_text = ["công ty báo lãi lớn", "giá vàng hôm nay tăng mạnh",
    "trận chung kết bóng đá rất hấp dẫn"]
new_seq = tokenizer.texts_to_sequences(new_text)
new_pad = pad_sequences(new_seq, maxlen=max_len)

pred = model.predict(new_pad)
for text, p in zip(new_text, pred):
    prob = p[0]
    label = 1 if prob > 0.5 else 0
    print(f"{text} -> {prob:.4f} => label={label}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.3333 - loss: 0.6968
Test Accuracy: 0.3333333432674408
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
công ty báo lãi lớn -> 0.4922 => label=0
giá vàng hôm nay tăng mạnh -> 0.4934 => label=0
trận chung kết bóng đá rất hấp dẫn -> 0.4908 => label=0
