In [3]:
documents = [
    "students study artificial intelligence",
    "students build artificial intelligence",
    "engineers develop intelligent systems",
    "artificial intelligence improves technology"
]

In [31]:
import numpy as np

tokenized = [doc.split() for doc in documents]

tokenized

[['students', 'study', 'artificial', 'intelligence'],
 ['students', 'build', 'artificial', 'intelligence'],
 ['engineers', 'develop', 'intelligent', 'systems'],
 ['artificial', 'intelligence', 'improves', 'technology']]

In [7]:
vocabulary = {}
count = 0
for doc in tokenized:
    for word in doc:
        if word not in vocabulary:
            count = count + 1
            vocabulary[word] = count

print(vocabulary)

{'students': 1, 'study': 2, 'artificial': 3, 'intelligence': 4, 'build': 5, 'engineers': 6, 'develop': 7, 'intelligent': 8, 'systems': 9, 'improves': 10, 'technology': 11}


### One-hot encoding by myself

In [32]:
def onehot_vector(sentence):
    onehot_res = []
    for word in sentence.split():
        temp = [0]*len(vocabulary)
        if word in vocabulary:
            temp[vocabulary[word] - 1] = 1
        onehot_res.append(temp)

    return onehot_res

In [56]:
onehot_vector("students study artificial intelligence")

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]]

In [34]:
onehot_vector("students study in artificial intelligence field")

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

### One-hot encoding by library (Sklearn)

In [35]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

tokenized

[['students', 'study', 'artificial', 'intelligence'],
 ['students', 'build', 'artificial', 'intelligence'],
 ['engineers', 'develop', 'intelligent', 'systems'],
 ['artificial', 'intelligence', 'improves', 'technology']]

In [34]:
values = tokenized[0] + tokenized[1] + tokenized[2] + tokenized[3]
values = sorted(values)
values

['artificial',
 'artificial',
 'artificial',
 'build',
 'develop',
 'engineers',
 'improves',
 'intelligence',
 'intelligence',
 'intelligence',
 'intelligent',
 'students',
 'students',
 'study',
 'systems',
 'technology']

#### Label Encoding

In [37]:
label_encoder = LabelEncoder()
encoded = label_encoder.fit_transform(values)
print("Label encoded: ", encoded)

Label encoded:  [ 0  0  0  1  2  3  4  5  5  5  6  7  7  8  9 10]


#### Label Encoding loại bỏ từ trùng lặp

In [35]:
unique_values = list(set(values))
unique_values

['intelligence',
 'students',
 'artificial',
 'improves',
 'study',
 'systems',
 'develop',
 'engineers',
 'intelligent',
 'technology',
 'build']

In [53]:
encoded2 = label_encoder.fit_transform(sorted(unique_values))
print("Label encoded: ", encoded2)

Label encoded:  [ 0  1  2  3  4  5  6  7  8  9 10]


#### One-hot encoding

In [59]:
onehot_encoder = OneHotEncoder()
onehot_encoded = onehot_encoder.fit_transform(tokenized).toarray()

print(tokenized)
print("Onehot encoded: \n", onehot_encoded)

[['students', 'study', 'artificial', 'intelligence'], ['students', 'build', 'artificial', 'intelligence'], ['engineers', 'develop', 'intelligent', 'systems'], ['artificial', 'intelligence', 'improves', 'technology']]
Onehot encoded: 
 [[0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.]]


### Bag of Words by myself

In [58]:
vocabulary = {word:i+1 for i,word in enumerate(sorted(unique_values))}
vocabulary

{'artificial': 1,
 'build': 2,
 'develop': 3,
 'engineers': 4,
 'improves': 5,
 'intelligence': 6,
 'intelligent': 7,
 'students': 8,
 'study': 9,
 'systems': 10,
 'technology': 11}

In [59]:

def bow_vector(sentence):
    vector = [0]*len(vocabulary)
    for word in sentence.split():
        if word in vocabulary:
            vector[vocabulary[word] - 1] += 1

    return vector

In [60]:
bow_vector("students A and students B study in artificial intelligence to improves technology")

[1, 0, 0, 0, 1, 1, 0, 2, 1, 0, 1]

In [61]:
bow_vector("students study artificial intelligence")


[1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0]

In [62]:
bow_vector("students build artificial intelligence")


[1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0]

In [63]:
bow_vector("engineers develop intelligent systems")


[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0]

In [64]:
bow_vector("artificial intelligence improves technology")

[1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1]

### Bag of Words by library (Sklearn)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
bow_vectored = vectorizer.fit_transform(documents)

print(bow_vectored.toarray())

[[1 0 0 0 0 1 0 1 1 0 0]
 [1 1 0 0 0 1 0 1 0 0 0]
 [0 0 1 1 0 0 1 0 0 1 0]
 [1 0 0 0 1 1 0 0 0 0 1]]
